### PR TITLE
Workaround for people using local caching DNS server and DNSCrypt

### PR DESCRIPTION
**Pull request by tannerb**

### CODE REVIEW

**Comment by sagebind** [comment]
This essentially reverts the fixes to resolve #2, but I haven't actually figured out what's going on in either case. What system are you using, and what is your output of `dig +short myip.opendns.com`?

**Comment by tannerb** [comment]
I'm using Arch linux, using dnscrypt-proxy and unbound as a local caching DNS server, as my ISP hijacks all DNS traffic.

`/usr/bin/dig +short myip.opendns.com` gives nothing
`/usr/bin/dig +short myip.opendns.com @resolver1.opendns.com` gives my ip

Output of `dig myip.opendns.com`

```
~/.l/s/o/p/weather   master *  functions  command dig myip.opendns.com             Mon Oct 12 20:54:06 CDT 2015

; <<>> DiG 9.10.3 <<>> myip.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40587
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;myip.opendns.com.              IN      A

;; AUTHORITY SECTION:
opendns.com.            1403    IN      SOA     auth1.opendns.com. noc.opendns.com. 1444675210 16384 2048 1048576 2560

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Oct 12 20:55:22 CDT 2015
;; MSG SIZE  rcvd: 91
```

and
`dig myip.opendns.com @resolver1.opendns.com`

```
; <<>> DiG 9.10.3 <<>> myip.opendns.com @resolver1.opendns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48130
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;myip.opendns.com.              IN      A

;; ANSWER SECTION:
myip.opendns.com.       0       IN      A       50.72.44.172

;; Query time: 38 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Mon Oct 12 20:57:33 CDT 2015
;; MSG SIZE  rcvd: 61
```

**Comment by tannerb** [comment]
The best path to take may be a user level setting to specify which route to take

**Comment by sagebind** [comment]
I get a similar output to yours. Perhaps assume to use `dig +short myip.opendns.com @resolver1.opendns.com` unless a "use default resolver" option is set?

**Comment by sagebind** [comment]
I'll go about adding a user setting to configure this. Closing since there is a better solution.

**Pull request closed without merging**
